# Generated by Django 5.0.4 on 2025-01-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_filecategory_managedfile_reporttemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentreport',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='department',
        ),
        migrations.AlterUniqueTogether(
            name='departmentreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='departmentreport',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentreport',
            name='section',
        ),
        migrations.RemoveField(
            model_name='departmentreport',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='reportversion',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reportattachment',
            name='report',
        ),
        migrations.RemoveField(
            model_name='managedfile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='managedfile',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='reportattachment',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='templatesection',
            name='section',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='templatesection',
            name='template',
        ),
        migrations.RemoveField(
            model_name='reportversion',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='DepartmentReport',
        ),
        migrations.DeleteModel(
            name='FileCategory',
        ),
        migrations.DeleteModel(
            name='ManagedFile',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportAttachment',
        ),
        migrations.DeleteModel(
            name='ReportSection',
        ),
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
        migrations.DeleteModel(
            name='TemplateSection',
        ),
        migrations.DeleteModel(
            name='ReportVersion',
        ),
    ]
