# Generated by Django 5.0.4 on 2025-01-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_task_progress_task_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='year',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='end_year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='start_year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
