# Generated by Django 5.0.4 on 2025-01-19 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_report_comment_approvalflowhistory_approvalflow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalflowhistory',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='approvalflowhistory',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='report',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_by',
        ),
        migrations.AddField(
            model_name='report',
            name='faculty',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='annual_reports/')),
                ('submitted_to_principal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annual_reports', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
        ),
        migrations.DeleteModel(
            name='ApprovalFlow',
        ),
        migrations.DeleteModel(
            name='ApprovalFlowHistory',
        ),
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
    ]
