# Generated by Django 5.0.4 on 2025-01-19 12:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_approvalflowhistory_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='faculty',
        ),
        migrations.AddField(
            model_name='report',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.academicyear'),
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_reports', to='home.department'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to HOD'), ('approved', 'Approved by HOD'), ('rejected', 'Rejected by HOD')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='AnnualDepartmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('compiled_file', models.FileField(upload_to='annual_reports/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Principal'), ('approved', 'Approved by Principal'), ('rejected', 'Rejected by Principal')], default='draft', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
            options={
                'unique_together': {('department', 'academic_year')},
            },
        ),
        migrations.DeleteModel(
            name='AnnualReport',
        ),
    ]
